#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
paramGroups.py
------------------------------------
parameter group to fill in ParamGroup
'''

param_groups = {
	"p-bromophenyl phenyl ether":"organics, other",
	"propargite":"organics, pesticide",
	"carbonate as co3":"inorganics, major, non-metals",
	"sulfometuron methyl":"organics, pesticide",
	"benzo(g,h,i)perylene":"organics, other",
	"n-nitrosodimethylamine":"information",
	"2,4-d":"organics, pesticide",
	"tamoxifen":"organics, other",
	"seston":"biological",
	"bromobenzene":"organics, other",
	"cobalt":"inorganics, minor, metals",
	"oxychlordane":"organics, pesticide",
	".delta.-hexachlorocyclohexane":"organics, pesticide",
	"e. coli":"microbiological",
	"hcfc-21":"organics, other",
	"1,6-dimethylnaphthalene":"organics, other",
	"wind velocity":"physical",
	"zirconium":"inorganics, minor, metals",
	"dissolved calcium":"inorganics, major, metals",
	"surface area":"information",
	"butylate":"organics, pesticide",
	"ammonia":"nutrient",
	"dead fish, severity":"biological",
	"orthophosphate":"nutrient",
	"ammonium as nh4":"nutrient",
	"sulfamethoxazole":"organics, other",
	"1,3,5-triazin-2(1h)-one, 4-(ethylamino)-6-[(1-methylethyl)amino]-":"organics, pesticide",
	"1,1,2,2-tetrachloroethane":"organics, other",
	"2-nitroaniline":"organics, other",
	"manganese, dissolved":"inorganics, minor, metals",
	"turbidity severity":"physical",
	"ethyl tert-butyl ether":"organics, other",
	"alpha, dissolved":"radiochemical",
	"1-methylpyrene":"organics, other",
	"gross alpha radioactivity, (thorium-230 ref std)":"radiochemical",
	"dissolved magnesium":"inorganics, major, metals",
	"potassium-40":"radiochemical",
	"dichlorvos":"organics, pesticide",
	"propachlor":"organics, pesticide",
	"chemical oxygen demand":"physical",
	"2,4-d methyl ester":"organics, pesticide",
	"methylcyclohexane":"organics, other",
	"barium":"inorganics, minor, metals",
	"dichlorobenzenes, total":"organics, other",
	"tributyl phosphate":"organics, other",
	"thorium-232":"radiochemical",
	"monuron":"organics, pesticide",
	"cis-1,3-dichloropropene":"organics, pesticide",
	"2-chloro-4-isopropylamino-6-amino-s-triazine":"organics, pesticide",
	"nitrate":"nutrient",
	"dichlorprop":"organics, pesticide",
	"1,1-dichloropropene":"organics, other",
	"chromium, hex, as cr":"inorganics, minor, metals",
	"phosmetoxon":"organics, pesticide",
	"di(2-ethylhexyl) phthalate":"organics, other",
	"suspended sediment discharge":"sediment",
	"evaporation":"physical",
	"di-n-butyl phthalate":"organics, other",
	"malathion-d10":"organics, pesticide",
	"bis(2-chloroethoxy)methane":"organics, other",
	"benzene, 1,1'-oxybis[2,4-dibromo-":"organics, other",
	"n-hexane":"organics, other",
	"2-methylanthracene":"organics, other",
	"p-dichlorobenzene":"organics, pesticide",
	"hydrocarbons, petroleum":"organics, other",
	"p-nitroaniline":"organics, other",
	"thorium-234":"radiochemical",
	"norethisterone":"organics, other",
	"imidacloprid":"organics, pesticide",
	"methyl ethyl ketone":"toxicity",
	"dextromethorphan hydrobromide":"organics, other",
	"alkalinity, phenolphthalein (total hydroxide+1/2 carbonate)":"inorganics, major, non-metals",
	"antimony, total":"inorganics, minor, non-metals",
	"propazine":"organics, pesticide",
	"desipramine":"organics, other",
	"cholesterol":"organics, other",
	"propane":"organics, other",
	"vernolate":"organics, pesticide",
	"methane":"organics, other",
	"isopropyl ether":"organics, other",
	"methyl parathion":"organics, pesticide",
	"phosphorus 0 as p":"nutrient",
	"alkalinity, caco3 stability":"inorganics, major, non-metals",
	"propanenitrile":"organics, other",
	"dissolved zinc":"inorganics, minor, metals",
	"total chlorine":"inorganics, major, non-metals",
	"velocity-discharge":"physical",
	"carbonaceous biochemical oxygen demand, non-standard conditions":"physical",
	"propanil":"organics, pesticide",
	"thiabendazole":"organics, pesticide",
	"1,3,5-trimethylbenzene":"organics, other",
	"acanthamoeba":"microbiological",
	"fluoranthene-1,2,3,4,5,6,7,8,9,10-d10":"organics, other",
	"elevation, water surface, msl":"physical",
	"sulfide":"inorganics, major, non-metals",
	"pheophytin a":"biological",
	"1,1-dichloroethylene":"organics, other",
	"copper, free":"inorganics, minor, metals",
	"benomyl":"organics, pesticide",
	"total suspended solids":"physical",
	"oxamyl":"organics, pesticide",
	"hexazinone":"organics, pesticide",
	"bicarbonate as caco3":"inorganics, major, non-metals",
	"1-butanol":"organics, other",
	"carbonaceous biochemical oxygen demand, standard conditions":"physical",
	"sulfur-34/sulfur-32 ratio":"stable isotopes",
	"coliform (tcr)":"microbiological",
	"caffeine":"organics, other",
	"fenamiphos":"organics, pesticide",
	"alprazolam":"organics, other",
	"carbon tetrachloride":"toxicity",
	"lithium, total":"inorganics, minor, metals",
	"fecal streptococcus group bacteria":"microbiological",
	"pentachlorophenol":"organics, pesticide",
	"1,3-dichloropropane":"organics, pesticide",
	"phosphorus, total":"nutrient",
	"inorganic nitrogen (nitrate and nitrite) as n":"nutrient",
	"2-chloroethyl vinyl ether":"organics, other",
	"benzo[ghi]perylene":"organics, other",
	"anions total":"physical",
	"dichlorodifluoromethane":"organics, other",
	"chlorate":"inorganics, minor, non-metals",
	"charge balance":"physical",
	"dicrotophos":"organics, pesticide",
	"calcium hardness":"physical",
	"1,1,2-trichloroethane":"organics, other",
	"strontium":"inorganics, minor, metals",
	"barometric pressure":"physical",
	"ethanamine, 2-(diphenylmethoxy)-n,n-dimethyl-":"organics, other",
	"total lead":"inorganics, minor, metals",
	"ethanol":"organics, other",
	"boron":"inorganics, minor, non-metals",
	"gross beta radioactivity, (strontium-yttrium-90 ref std)":"radiochemical",
	"bendiocarb":"organics, pesticide",
	"benzo(b)fluoranthene":"organics, other",
	"1,3-dichloropropene":"organics, pesticide",
	"permethrin":"organics, pesticide",
	"total volatile solids":"physical",
	"simazine":"information",
	"fonofos":"organics, pesticide",
	"malaoxon":"organics, pesticide",
	"phytoplankton":"biological",
	"tantalum":"inorganics, minor, metals",
	"ethane":"organics, other",
	"p-chlorotoluene":"organics, other",
	"cesium":"inorganics, minor, metals",
	"trihalomethanes":"organics, other",
	"2,3,6-trimethylnaphthalene":"organics, other",
	"dimethachlor esa":"organics, pesticide",
	"chrysene":"organics, other",
	"terbuthylazine":"organics, pesticide",
	"iron, suspended":"inorganics, minor, metals",
	"3,3'-dichlorobenzidine":"organics, other",
	"3,4-dichlorophenyl isocyanate":"organics, other",
	"hexachlorobutadiene":"organics, other",
	"dissolved aluminum":"inorganics, minor, metals",
	"1,2-dimethylnaphthalene":"organics, other",
	"organic phosphorus":"nutrient",
	"4-nitroaniline":"organics, other",
	"sulfate":"inorganics, major, non-metals",
	"acidity, m.o. (caco3)":"inorganics, major, non-metals",
	"cocaine-d3":"organics, other",
	"stream stage":"physical",
	"acetochlor":"organics, pesticide",
	"iodine":"inorganics, minor, non-metals",
	"biomass, periphyton":"biological",
	"solar irradiation, local":"physical",
	"total solids":"physical",
	"total polychlorinated biphenyls (pcb)":"organics, pcbs",
	"2,2-dichloropropane":"organics, other",
	"bacteria mixture, unspecified":"microbiological",
	"m-nitroaniline":"organics, other",
	"1,1,1-trichloroethane":"organics, other",
	"molinate":"organics, pesticide",
	"dibromoacetic acid":"organics, other",
	"hardness, ca, mg":"physical",
	"carboxin":"organics, pesticide",
	"niobium":"inorganics, minor, metals",
	"mestranol":"organics, other",
	"3-hydroxycarbofuran":"organics, pesticide",
	"strontium-90 and/or yttrium-90":"radiochemical",
	"carbophenothion":"organics, pesticide",
	"chlorothalonil":"organics, pesticide",
	"methyl salicylate":"organics, other",
	"acenaphthene-d10":"organics, other",
	"benzo(k)fluoranthene":"organics, other",
	"phenanthrene":"organics, other",
	"cobalt, total":"inorganics, minor, metals",
	"radon-222":"radiochemical",
	"cobalt-60":"radiochemical",
	"phorate":"organics, pesticide",
	"diphenamid":"organics, pesticide",
	"bromine":"inorganics, minor, non-metals",
	"osmium":"inorganics, minor, metals",
	"diazepam-d5":"organics, other",
	"hydrocarbons, volatile":"organics, other",
	"paraquat":"organics, pesticide",
	"apparent color":"physical",
	"plutonium-238":"radiochemical",
	"butachlor esa":"organics, pesticide",
	"sulfur":"inorganics, major, non-metals",
	"stream width measure":"information",
	"3,3',4,4',5,5'-hexachlorobiphenyl":"organics, pcbs",
	"mirex":"organics, pesticide",
	"ronnel":"organics, pesticide",
	"dimethoate":"organics, pesticide",
	"hexane":"organics, other",
	"rbp stream depth - run":"physical",
	"acifluorfen":"organics, pesticide",
	"titanium":"inorganics, minor, metals",
	"2,3,4,6-tetrachlorophenol":"organics, pesticide",
	"di-n-octyl phthalate":"organics, other",
	"gasoline":"organics, other",
	"parathion (ethyl)":"organics, pesticide",
	"carbon, total":"inorganics, major, non-metals",
	"dissolved selenium":"inorganics, minor, non-metals",
	"2-methylphenol":"organics, pesticide",
	"cacodylic acid":"organics, pesticide",
	"dissolved nitrate: no3":"nutrient",
	"nitrogen-ammonia as (n)":"nutrient",
	"cations-anions":"physical",
	"p-cresol":"organics, pesticide",
	"lindane":"organics, pesticide",
	"aniline":"organics, other",
	"dysprosium":"inorganics, minor, metals",
	"fluorene":"organics, other",
	"stream flow, mean. daily":"physical",
	"depth, secchi disk depth":"information",
	"dinoseb":"organics, pesticide",
	"triclocarban":"organics, other",
	"2,6-dimethylnaphthalene":"organics, other",
	"2-propanol, 1,3-dichloro-, phosphate (3:1)":"organics, other",
	"cyclopenta[g]-2-benzopyran, 1,3,4,6,7,8-hexahydro-4,6,6,7,8,8-hexamethyl-":"organics, other",
	"ammonium as n":"nutrient",
	"sulfotep":"organics, pesticide",
	"p-chloro-m-cresol":"organics, pesticide",
	"total sodium":"inorganics, major, metals",
	"cfc-12":"organics, other",
	"diuron":"information",
	"cfc-11":"organics, other",
	"hydrogen":"inorganics, major, non-metals",
	"bromoxynil":"organics, pesticide",
	"calcium carbonate as caco3":"inorganics, major, non-metals",
	"1-naphthol":"organics, pesticide",
	"thallium":"inorganics, minor, metals",
	"helium":"inorganics, minor, non-metals",
	"acetochlor oa":"organics, pesticide",
	"warfarin":"organics, other",
	"total manganese":"inorganics, minor, metals",
	"2-chlorophenol":"organics, other",
	"bismuth, total":"inorganics, minor, metals",
	"anion/cation ratio":"physical",
	"iron-59":"radiochemical",
	"myclobutanil":"organics, pesticide",
	"beta, suspended":"radiochemical",
	"morpholine, 3-methyl-2-phenyl-":"organics, other",
	"xylenes mix of m + o + p":"organics, other",
	"chemical oxygen demand, (high level)":"physical",
	"volatile dissolved solids":"physical",
	".alpha.-endosulfan":"organics, pesticide",
	"alachlor oa":"organics, pesticide",
	"depth, data-logger (ported)":"information",
	"imazethapyr":"organics, pesticide",
	"isofenphos":"organics, pesticide",
	"inorganic nitrogen (nitrate and nitrite)":"nutrient",
	"methylene chloride":"organics, other",
	"krypton":"inorganics, minor, non-metals",
	"nitrobenzene":"organics, other",
	"2-pyrrolidinone, 1-methyl-5-(3-pyridinyl)-, (5s)-":"organics, other",
	"dimethenamid esa":"organics, pesticide",
	"simvastatin":"organics, other",
	"trans-1,3-dichloropropene":"organics, pesticide",
	"cadmium":"inorganics, minor, metals",
	"2,6-diethylaniline":"organics, pesticide",
	"1-methylfluorene":"organics, other",
	"chloride":"inorganics, major, non-metals",
	"scandium":"inorganics, minor, metals",
	"m-dichlorobenzene":"organics, other",
	"iron, ion (fe2+)":"inorganics, minor, metals",
	"flumetsulam":"organics, pesticide",
	"total kjeldahl nitrogen (in water mg/l)":"nutrient",
	"benzene, pentachloromethoxy-":"organics, pesticide",
	"1,2-diphenylhydrazine":"organics, other",
	"sum of anions":"physical",
	"morphine":"organics, other",
	"vanadium":"inorganics, minor, metals",
	"bromodichloromethane":"organics, other",
	"deuterium/hydrogen ratio":"stable isotopes",
	"dissolved cadmium":"inorganics, minor, metals",
	"coal":"organics, other",
	"2-methylnaphthalene":"organics, other",
	"aroclor 1232":"organics, pcbs",
	"antimony-125":"radiochemical",
	"nitrogen, mixed forms (nh3), (nh4), organic, (no2) and (no3)":"nutrient",
	"sutan":"organics, pesticide",
	"total coliforms":"microbiological",
	"methidathion":"organics, pesticide",
	"phenobarbital-d5":"organics, other",
	"o-chlorophenol":"organics, other",
	"4-methyl-2-pentanone":"organics, other",
	"benzenemethanol, .alpha.-[(1r)-1-aminoethyl]-, hydrochloride (1:1), (.alpha.s)-rel-":"organics, other",
	"gas bubble severity":"physical",
	"diquat":"organics, pesticide",
	"copper":"inorganics, minor, metals",
	"aroclor 1016":"organics, pcbs",
	"monocrotophos":"organics, pesticide",
	"1,2,3-trichlorobenzene":"organics, other",
	"gemfibrozil":"organics, other",
	"bensulfuron-methyl":"organics, pesticide",
	"narstest~enterococci samp":"microbiological",
	"phosphate-phosphorus":"nutrient",
	"ranitidine":"organics, other",
	"nitrogen":"nutrient",
	"bentazon":"organics, pesticide",
	"triallate":"organics, pesticide",
	"ammonia-nitrogen as n":"nutrient",
	"4-chloro-2-methylphenol":"organics, pesticide",
	"chlorpyrifos":"organics, pesticide",
	"dissolved lead":"inorganics, minor, metals",
	"hydrogen ion":"inorganics, major, non-metals",
	"tritium":"radiochemical",
	"pyridine":"organics, other",
	"methanol":"organics, other",
	"carbofuran-d3":"organics, pesticide",
	"halon 1011":"organics, other",
	"combined chlorine":"inorganics, major, non-metals",
	"amitriptyline":"organics, other",
	"guthion":"organics, pesticide",
	"bezafibrate":"organics, other",
	"acetochlor esa":"organics, pesticide",
	"1,2-dibromo-3-chloropropane":"organics, pesticide",
	"m-xylene":"organics, other",
	"chromium(vi)":"inorganics, minor, metals",
	"free residual chlorine":"inorganics, major, non-metals",
	"endrin ketone":"organics, pesticide",
	"cis-(-)-2-[(dimethylamino)methyl]-1[3-methoxyphenyl]-cyclohexanol":"organics, other",
	"metsulfuron-methyl":"organics, pesticide",
	"alkalinity":"inorganics, major, non-metals",
	"orthophosphate as p":"nutrient",
	"halogenated organics":"organics, other",
	"3,5-dinitroaniline":"organics, other",
	"alachlor esa":"information",
	"bromochloromethane":"organics, other",
	"radon":"radiochemical",
	"moisture content":"physical",
	"pebulate":"organics, pesticide",
	"hexachlorobenzene":"organics, pesticide",
	"tthm":"organics, other",
	"acetic acid":"organics, other",
	"acetone":"organics, other",
	"trihalomethanes (four), total, from sdwa npdwr":"organics, other",
	"alpha particle":"radiochemical",
	"molybdenum":"inorganics, minor, metals",
	"oxygen":"inorganics, major, non-metals",
	"gross alpha radioactivity, (nat-uranium ref std)":"radiochemical",
	"phenanthridine":"organics, other",
	"potassium":"inorganics, major, metals",
	"tetrachlorobiphenyl":"organics, pcbs",
	"biochemical oxygen demand, non-standard conditions":"physical",
	"cocaine hydrochloride":"organics, other",
	"ethylene dibromide":"organics, pesticide",
	"2,4-d-13c6":"organics, pesticide",
	"europium-154":"radiochemical",
	"thiamethoxam":"organics, pesticide",
	"chlordane, technical, and/or chlordane metabolites":"organics, pesticide",
	"1-methylnaphthalene":"organics, other",
	"total iron":"inorganics, minor, metals",
	"hardness, ca, mg as caco3":"physical",
	"dichloroacetonitrile":"organics, other",
	"toluene":"organics, other",
	"2,4,5-trichlorophenol":"organics, pesticide",
	"bis(2-chloro-1-methylethyl) ether":"organics, other",
	"hydroxide":"inorganics, major, non-metals",
	"total nickel":"inorganics, minor, metals",
	"o-chlorotoluene":"organics, other",
	"pentachloroethane":"organics, other",
	"carbon dioxide":"inorganics, major, non-metals",
	"thorium-230":"radiochemical",
	"nitrite":"nutrient",
	"permethrin (mixed, cis, trans)":"organics, pesticide",
	"caffeine-trimethyl-13c3":"organics, other",
	"terbacil":"organics, pesticide",
	".beta.-endosulfan":"organics, pesticide",
	"acenaphthene":"organics, other",
	"o,p'-ddd":"organics, pesticide",
	"s-ethyl dipropylthiocarbamate":"organics, pesticide",
	"progesterone":"organics, other",
	"aldrin":"organics, pesticide",
	"o-cresol":"organics, pesticide",
	"parathion":"organics, pesticide",
	"gage height":"physical",
	"thorium-228":"radiochemical",
	"dissolved chromium":"inorganics, minor, metals",
	"monochloroacetic acid":"organics, other",
	"wave height":"physical",
	"dissolved barium":"inorganics, minor, metals",
	"phosphoric acid, diethyl 6-methyl-2-(1-methylethyl)-4-pyrimidinyl ester":"organics, pesticide",
	"1,2,3,5-tetramethylbenzene":"organics, other",
	"fluorine":"inorganics, major, non-metals",
	"oryzalin":"organics, pesticide",
	"acrylamide":"organics, other",
	"acetonitrile":"organics, other",
	"spectracide":"organics, pesticide",
	"chlorine dioxide":"inorganics, major, non-metals",
	"fenuron":"organics, pesticide",
	"bicarbonate":"inorganics, major, non-metals",
	"hardness, magnesium":"physical",
	"fecal streptococcus":"microbiological",
	"tds":"physical",
	"2,4-dinitrophenol":"organics, other",
	"iodine-131":"radiochemical",
	"ethion":"organics, pesticide",
	"ideno(1,2,3-cd)pyrene":"organics, other",
	"alpha, suspended":"radiochemical",
	"2,3,7,8-tcdd":"organics, other",
	"transpermethrin":"organics, pesticide",
	"strontium-90":"radiochemical",
	"chlorine":"inorganics, major, non-metals",
	"atenolol-d7":"organics, other",
	"2,3,7,8-tetrachlorodibenzo-p-dioxin":"organics, other",
	"residual chlorine":"inorganics, major, non-metals",
	"cholestan-3-ol, (3.beta.,5.beta.)-":"organics, other",
	"lead summary":"inorganics, minor, metals",
	"total boron":"inorganics, minor, non-metals",
	"methomyl":"organics, pesticide",
	"stream flow, instantaneous":"physical",
	"sediment":"sediment",
	"silicon":"inorganics, major, non-metals",
	"terbium":"inorganics, minor, metals",
	"benzo[c]cinnoline":"organics, other",
	"dextronorgestrel":"organics, other",
	"dissolved boron":"inorganics, minor, non-metals",
	"styrene":"organics, other",
	"cyanide":"inorganics, minor, non-metals",
	"isobutyl alcohol":"organics, other",
	"suspended sediment concentration (ssc)":"sediment",
	"amitriptyline (+/-)-e-10-hydroxylated":"organics, other",
	"2,4,5-trichlorobiphenyl":"organics, pcbs",
	"bupropion":"organics, pesticide",
	"phenol, 4-(1-methyl-1-phenylethyl)-":"organics, other",
	"benzo[a]pyrene":"organics, other",
	"dissolved oxygen (do)":"inorganics, major, non-metals",
	"wind direction":"physical",
	"methyl bromide":"organics, pesticide",
	"sodium adsorption ratio [(na)/(sq root of 1/2 ca + mg)]":"inorganics, major, metals",
	"demeton":"organics, pesticide",
	"benzene, 1-chloro-2-[2,2,2-trichloro-1-(4-chlorophenyl)ethyl]-, 1,1'-(2,2,2-trichloroethylidene)bis[4-chlorobenzene], 1-chloro-2-[2,2-dichloro-1-(4-chlorophenyl)ethyl]benzene], 1,1'-(2,2-dichloroethylidene)bis[4-chlorobenzene], 1-chloro-2-[2,2-dichloro-1-(4-chlorophenyl)ethenyl]benzene, and 1,1'-(dichloroethenylidene)bis[4-chlorobenzene] and metabolites":"toxicity",
	"2,4,5-t":"information",
	"2-nitrophenol":"organics, other",
	"praseodymium":"inorganics, minor, metals",
	"metribuzin":"organics, pesticide",
	"methiocarb":"organics, pesticide",
	"diesel fuel":"organics, other",
	"total calcium":"inorganics, major, metals",
	"cyfluthrin":"organics, pesticide",
	"o-nitrophenol":"organics, other",
	"kjeldahl nitrogen as n":"nutrient",
	"mercury":"inorganics, minor, metals",
	"water transparency, secchi disc":"physical",
	"tebuconazole":"organics, pesticide",
	"tetrachloroethylene":"toxicity",
	"aldicarb sulfoxide":"organics, pesticide",
	"isobutanol":"organics, other",
	"carbonate":"inorganics, major, non-metals",
	"phosphate, tot. dig. (as p)":"nutrient",
	"oxidation reduction potential (orp)":"physical",
	"pyrene":"organics, other",
	"ethanoic acid":"organics, other",
	"thulium":"inorganics, minor, metals",
	"baygon":"organics, pesticide",
	"benzidine":"organics, other",
	"benzphetamine hydrochloride":"organics, other",
	"light attenuation, depth at 99%":"physical",
	"aroclor 1262":"organics, pcbs",
	"tert-amyl methyl ether":"organics, other",
	"2,2'-biquinoline":"organics, other",
	"trash, debris, floatables":"physical",
	"tetrahydrofuran":"organics, other",
	"ruthenium":"inorganics, minor, metals",
	"endrin aldehyde":"organics, pesticide",
	"sulfamethazine":"organics, other",
	"pronamide":"organics, pesticide",
	"argon":"inorganics, minor, non-metals",
	"dissolved manganese":"inorganics, minor, metals",
	"formaldehyde":"organics, other",
	"bromochloroacetic acid":"organics, other",
	"propham":"organics, pesticide",
	"nitrite as no2":"nutrient",
	"m-cresol":"organics, other",
	"heptachlor epoxide":"organics, pesticide",
	"boron, total":"inorganics, minor, non-metals",
	"norfluoxetine-d6":"organics, other",
	"ethanol, 2-(4-nonylphenoxy)-":"organics, other",
	"bismuth":"inorganics, minor, metals",
	"disulfoton sulfone":"organics, pesticide",
	"total barium":"inorganics, minor, metals",
	"2,4,6-trichlorophenol":"organics, pesticide",
	"erbium":"inorganics, minor, metals",
	"aroclor 1260":"organics, pcbs",
	"benz[a]anthracene":"organics, other",
	"4,6-dinitro-o-cresol":"organics, pesticide",
	"aldicarb":"organics, pesticide",
	"extended diesel range organics c10-c36":"organics, other",
	"magnesium":"inorganics, major, metals",
	"1-chlorobutane":"organics, other",
	"strontium-87/strontium-86, ratio":"stable isotopes",
	"des-isopropyl-atrazine":"organics, pesticide",
	"atraton":"organics, pesticide",
	"2,4-dimethylphenol":"organics, pesticide",
	"specific conductivity":"physical",
	"biochemical oxygen demand, standard conditions":"physical",
	"clopyralid":"organics, pesticide",
	"methoxychlor":"organics, pesticide",
	"pendimethalin":"organics, pesticide",
	"zinc-65":"radiochemical",
	"4-chlorophenyl phenyl ether":"organics, other",
	"dicamba":"organics, pesticide",
	"benzo[e]pyrene":"organics, other",
	"nitrogen as n":"nutrient",
	"phenobarbital":"organics, other",
	"total molybdenum":"inorganics, minor, metals",
	"manganese":"inorganics, minor, metals",
	"malathion":"organics, pesticide",
	"surfactants -- cwa 304b":"organics, other",
	"ammonia as nh3":"nutrient",
	"total aluminum":"inorganics, minor, metals",
	"reservoir volume":"information",
	"chlorodibromomethane":"organics, other",
	"2-ethyl-6-methylaniline":"organics, pesticide",
	"chlorophyll a, uncorrected for pheophytin":"biological",
	"gross alpha, excl. radon & u":"radiochemical",
	"methyl tert-butyl ether":"organics, other",
	"radium-224":"radiochemical",
	"instream features, est. stream width":"physical",
	"3-nitroaniline":"organics, other",
	"sum of cations":"physical",
	"carbon-13/carbon-12 ratio":"stable isotopes",
	"metolachlor oa":"organics, pesticide",
	"iron":"inorganics, minor, metals",
	"chrysene-d12":"organics, other",
	"chloromethane":"organics, other",
	"2-chloro-6-ethylamino-4-amino-s-triazine":"organics, pesticide",
	"atrazine":"organics, pesticide",
	"2-methyl-4,6-dinitrophenol":"organics, pesticide",
	"glyphosate":"organics, pesticide",
	"monobromoacetic acid":"organics, other",
	"nitrate + nitrite as n":"nutrient",
	"nitrate-nitrogen":"nutrient",
	"alachlor":"organics, pesticide",
	"1,2-dichloroethane":"toxicity",
	"settleable solids":"physical",
	"volatile suspended solids":"physical",
	"triethyl citrate":"organics, other",
	"bromoform":"organics, other",
	"sotalol":"organics, other",
	"sulfate as s":"inorganics, major, non-metals",
	"total fixed solids":"physical",
	"manganese-54":"radiochemical",
	"hafnium":"inorganics, minor, metals",
	"dalapon":"organics, pesticide",
	"specific conductance":"physical",
	"acetaldehyde":"organics, other",
	"uranium-234/235/238":"radiochemical",
	"escherichia":"microbiological",
	"alpha-chlordane":"organics, pesticide",
	"1,4-dioxane":"organics, other",
	"carbonate as caco3":"inorganics, major, non-metals",
	"total magnesium":"inorganics, major, metals",
	"dissolved potassium":"inorganics, major, metals",
	"xenon":"inorganics, minor, non-metals",
	"flow":"physical",
	"3,5-dimethylphenol":"organics, other",
	"salinity":"physical",
	"carbonate (co3)":"inorganics, major, non-metals",
	"orthophosphate as po4":"nutrient",
	"rhodium":"inorganics, minor, metals",
	"ethylene glycol":"organics, other",
	"uv 254 -- sdwa npdwr":"physical",
	"tellurium":"inorganics, minor, non-metals",
	"triphenyl phosphate":"organics, other",
	"tris(2-butoxyethyl) phosphate":"organics, other",
	"3-methylindole":"organics, other",
	"carbophenothion-methyl":"organics, pesticide",
	"dibromomethane":"organics, other",
	"aroclor 1254":"organics, pcbs",
	"lead-212":"radiochemical",
	"strontium-89":"radiochemical",
	"sodium adsorption ratio":"inorganics, major, metals",
	"gold":"inorganics, minor, metals",
	"oil range organics":"organics, other",
	"total copper":"inorganics, minor, metals",
	"iron, dissolved":"inorganics, minor, metals",
	"chloral hydrate":"organics, other",
	"2-methyl-2-butanol":"organics, other",
	"particle size":"sediment",
	"vinyl 2-chloroethyl ether":"organics, other",
	"triclosan":"organics, other",
	"gadolinium":"inorganics, minor, metals",
	"total carbon":"inorganics, major, non-metals",
	"withdrawal rate":"information",
	"trichlorobiphenyl":"organics, pcbs",
	"acrylonitrile":"organics, pesticide",
	"picloram":"organics, pesticide",
	"depth":"information",
	"total iron-d max, dmr":"inorganics, minor, metals",
	"nitrogen, ammonium/ammonia ratio":"nutrient",
	"gross beta radioactivity, (cesium-137 ref std)":"radiochemical",
	"chloroethane":"organics, other",
	"depth, bottom":"information",
	"beryllium, total":"inorganics, minor, metals",
	"gross beta particle activity":"radiochemical",
	"aroclor 1221":"organics, pcbs",
	"total selenium":"inorganics, minor, non-metals",
	"radium-226/228":"radiochemical",
	"xylenes, total":"organics, other",
	"density of water at 20 deg c":"physical",
	"metalaxyl":"organics, pesticide",
	"ethanone, 1-[6-(1,1-dimethylethyl)-2,3-dihydro-1,1-dimethyl-1h-inden-4-yl]-":"organics, other",
	"nitrogen ion":"nutrient",
	"iprodione":"organics, pesticide",
	"2,4,5-tp":"organics, pesticide",
	"triclopyr":"organics, pesticide",
	"chlorophyll a":"biological",
	"chlorophyll c":"biological",
	"chlorophyll b":"biological",
	"asbestos":"inorganics, minor, non-metals",
	"cyanides amenable to chlorination (hcn & cn)":"inorganics, minor, non-metals",
	"combined uranium":"radiochemical",
	"cerium":"inorganics, minor, metals",
	"para-para ddd":"organics, pesticide",
	"para-para dde":"organics, pesticide",
	"dichlorobiphenyl":"organics, other",
	"phosphate, reactive":"nutrient",
	"2-chloro-4,6-diamino-s-triazine":"organics, pesticide",
	"alkalinity, carbonate":"inorganics, major, non-metals",
	"tebuthiuron":"organics, pesticide",
	"tris(2-chloroethyl) phosphate":"organics, other",
	"38-strontium-90":"radiochemical",
	"diazinon-d10":"organics, pesticide",
	"para-para ddt":"organics, pesticide",
	"azinphos-methyl":"organics, pesticide",
	"conductivity @ 25 c umhos/cm":"physical",
	"dissolved arsenic":"inorganics, minor, non-metals",
	"aluminum":"inorganics, minor, metals",
	"sodium carbonate":"physical",
	"gamma-chlordane":"organics, pesticide",
	"fecal coliforms":"microbiological",
	"triclosan,c13h10cl2o- derivative":"organics, other",
	"phenols and phenolic compounds":"organics, other",
	"p-chlorophenyl phenyl ether":"organics, other",
	"inorganic carbon":"inorganics, major, non-metals",
	"d9 (+/-)11-nor-9-carboxy-delta-thc":"organics, other",
	"ionic strength":"physical",
	"cation total":"physical",
	"erythromycin":"organics, other",
	"alkalinity, total as caco3":"inorganics, major, non-metals",
	"beta cypermethrin":"organics, pesticide",
	"reservoir storage":"information",
	".alpha.,.alpha.-dimethylphenethylamine":"organics, other",
	"total sample volume":"information",
	"nitrate as no3":"nutrient",
	"phenanthrene-d10":"organics, other",
	"t.k.n.":"nutrient",
	"turbidity":"physical",
	"total alkalinity as caco3":"inorganics, major, non-metals",
	"gross alpha radioactivity, (americium-241 ref std)":"radiochemical",
	"ammonia uptake":"nutrient",
	"thallium, total":"inorganics, minor, metals",
	"beta particle":"radiochemical",
	"hcfc-22":"organics, other",
	"total coliform":"microbiological",
	"alkalinity, total":"inorganics, major, non-metals",
	"conductivity":"physical",
	"velocity - stream":"physical",
	"n-propylbenzene":"organics, other",
	"methyl iodide":"organics, pesticide",
	"antimony":"inorganics, minor, non-metals",
	"chromium(iii)":"inorganics, minor, metals",
	"2,4-dichlorophenol":"organics, pesticide",
	"endrin":"organics, pesticide",
	"silicon as sio2":"inorganics, major, non-metals",
	"flow rate, instantaneous":"physical",
	"dichloroiodomethane":"organics, other",
	"neodymium":"inorganics, minor, metals",
	"total haloacetic acids (haa5)":"organics, other",
	"di(2-ethylhexyl) adipate":"organics, other",
	"vinyl acetate":"organics, other",
	"ammonia-nitrogen":"nutrient",
	"aldicarb sulfone":"organics, pesticide",
	"stigmastan-3-ol, (3.beta.)-":"organics, other",
	"anthraquinone":"organics, other",
	"zinc":"inorganics, minor, metals",
	"4-chloroaniline":"organics, pesticide",
	"diazinon":"organics, pesticide",
	"samarium":"inorganics, minor, metals",
	"phendimetrazine":"organics, other",
	"tribenuron-methyl":"organics, pesticide",
	"propiconazole":"organics, pesticide",
	"o-nitroaniline":"organics, other",
	"carbon":"inorganics, major, non-metals",
	"metolachlor":"organics, pesticide",
	"escherichia coli":"microbiological",
	"4-nitrophenol":"organics, pesticide",
	"ametryn":"organics, pesticide",
	"ice cover, floating or solid":"physical",
	"tert-butylbenzene":"organics, other",
	"gross alpha particle activity":"radiochemical",
	"benzoic acid":"organics, other",
	"partial pressure of dissolved gases":"physical",
	"trichloroacetic acid":"organics, other",
	"sodium":"inorganics, major, metals",
	"hardness, carbonate":"physical",
	"titanium, total":"inorganics, minor, metals",
	"hydrogen sulfide":"inorganics, major, non-metals",
	"alkalinity, bicarbonate as caco3":"inorganics, major, non-metals",
	"acetophenone":"organics, other",
	"chemical oxygen demand, (low level)":"physical",
	"1,2,4,5-tetrachlorobenzene":"organics, other",
	"phenol, 2-(1,1-dimethylethyl)-4-methoxy-":"organics, other",
	"depth, from ground surface to well water level":"physical",
	"isoborneol":"organics, other",
	"dibenz[a,h]anthracene":"organics, other",
	"uranium-238":"radiochemical",
	"bis(2-chloroethyl) ether":"organics, other",
	"2,4-db":"information",
	"algae, floating mats (severity)":"physical",
	"biphenyl":"organics, other",
	"color":"physical",
	"selenium":"inorganics, minor, non-metals",
	"detergent, severity":"physical",
	"cyanazine":"organics, pesticide",
	"uranium-234":"radiochemical",
	"uranium-235":"radiochemical",
	"uranium-236":"radiochemical",
	"1,2,4-trichlorobenzene":"organics, other",
	"depth, data-logger (non-ported)":"information",
	"mecoprop":"organics, pesticide",
	"ph, lab":"physical",
	"oil and grease":"organics, other",
	"methyl acrylate":"organics, other",
	"chlorpheniramine":"organics, other",
	"arsenic":"inorganics, minor, non-metals",
	"p-octylphenol":"organics, other",
	"chromium":"inorganics, minor, metals",
	"rhenium":"inorganics, minor, metals",
	"platinum":"inorganics, minor, metals",
	"carbazole":"organics, pesticide",
	"methyl methacrylate":"organics, other",
	"sulfur hexafluoride":"inorganics, minor, non-metals",
	"prometryn":"organics, pesticide",
	"chlorthal-monomethyl":"organics, pesticide",
	"diesel range organics":"organics, other",
	"chloroacetic acid":"organics, other",
	"naphthalene":"organics, other",
	"dissolved iron":"inorganics, minor, metals",
	"cloud cover":"physical",
	"flufenacet":"organics, pesticide",
	"ph":"physical",
	"iodide":"inorganics, minor, non-metals",
	".alpha.-hexachlorocyclohexane":"organics, pesticide",
	"dichlorovos":"organics, pesticide",
	"1,2,4-trimethylbenzene":"organics, other",
	"prometon":"information",
	"aminomethylphosphonic acid":"organics, pesticide",
	"chlorodifluoromethane (hcfc-22)":"organics, other",
	"dichloromethane":"organics, other",
	"benzeneacetic acid, .alpha.-methyl-4-(2-methylpropyl)-":"organics, other",
	"chlorite":"inorganics, major, non-metals",
	"acrolein":"organics, other",
	"3,3-dichlorobenzidine":"organics, other",
	"carbamazepine":"organics, other",
	"carbon disulfide":"organics, pesticide",
	"propoxur":"organics, pesticide",
	"n-butyl alcohol":"organics, other",
	"ytterbium":"inorganics, minor, metals",
	"oxyfluorfen":"organics, pesticide",
	"phosphate-phosphorus as p":"nutrient",
	"benzyl alcohol":"organics, other",
	"2,4-pyrimidinediamine, 5-[(3,4,5-trimethoxyphenyl)methyl]-":"organics, other",
	"algal growth potential":"biological",
	"anthracene":"organics, other",
	"azobenzene":"organics, pesticide",
	"1-methylphenanthrene":"organics, other",
	"hardness, non-carbonate":"physical",
	"lanthanum":"inorganics, minor, metals",
	"chlorimuron-ethyl":"organics, pesticide",
	"dibromoacetonitrile":"organics, other",
	"isopropanol":"organics, other",
	"sildenafil":"organics, other",
	"acidity as caco3":"inorganics, major, non-metals",
	"sulfamethoxazole-13c6":"organics, other",
	"calcium":"inorganics, major, metals",
	"dissolved nickel":"inorganics, minor, metals",
	"n,n-diethyl-m-toluamide":"organics, pesticide",
	"uranium 238/234 ratio":"radiochemical",
	"bicarbonate as hco3":"inorganics, major, non-metals",
	"trichlorotrifluoroethane":"organics, other",
	"benzoylecgonine-d3":"organics, other",
	"chlorthal-dimethyl":"organics, pesticide",
	"organic carbon":"organics, other",
	"chloramphenicol":"organics, other",
	"sec-butylbenzene":"organics, other",
	"total potassium":"inorganics, major, metals",
	"total chromium":"inorganics, minor, metals",
	"rbp stream velocity":"physical",
	"molybdenum, total":"inorganics, minor, metals",
	"quinoline":"organics, other",
	"anion deficit":"physical",
	"ethanimidothioic acid, n-hydroxy-, methyl ester":"organics, pesticide",
	"eptc":"organics, pesticide",
	"terbufos":"organics, pesticide",
	"stream velocity":"physical",
	"o-xylene":"organics, other",
	"ethylene":"organics, other",
	"selenium-75":"radiochemical",
	"acenaphthylene":"organics, other",
	"dissolved mercury":"inorganics, minor, metals",
	"butylbenzyl phthalate":"organics, other",
	"alkalinity, hydroxide as caco3":"inorganics, major, non-metals",
	"radium-228":"radiochemical",
	"trichloroethylene":"toxicity",
	"propachlor esa":"organics, pesticide",
	"ethene, 1,2-dibromo-":"organics, pesticide",
	"zooplankton":"biological",
	"dcpa":"organics, pesticide",
	"floating debris, severity":"physical",
	"bromomethane":"organics, pesticide",
	"holmium":"inorganics, minor, metals",
	"vinyl bromide":"organics, other",
	"lithium":"inorganics, minor, metals",
	"propachlor oa":"organics, pesticide",
	"siduron":"organics, pesticide",
	"methyl paraoxon":"organics, pesticide",
	"ethylbenzene":"organics, other",
	"4-methylphenol":"organics, pesticide",
	"estradiol":"organics, other",
	"tribromomethane":"organics, other",
	"benfluralin":"organics, pesticide",
	"esfenvalerate":"organics, pesticide",
	"diazepam":"organics, other",
	"gran acid neutralizing capacity":"inorganics, major, non-metals",
	"chloroform":"organics, other",
	"o-ethyltoluene":"organics, other",
	".alpha.-bhc":"organics, pesticide",
	"chloropyrifos":"organics, pesticide",
	"cis-chlordane":"organics, pesticide",
	"trans-1,4-dichloro-2-butene":"organics, other",
	"tefluthrin":"organics, pesticide",
	"n-nitrosodi-n-propylamine":"organics, other",
	"alpha emitting radium isotopes":"radiochemical",
	"bis(chloromethyl) ether":"organics, other",
	"chloramben-methyl":"organics, pesticide",
	"benzo(a)anthracene":"organics, other",
	"depth of pond or reservoir in feet":"physical",
	"2-hexanone":"organics, other",
	"benzo[k]fluoranthene":"organics, other",
	"sodium, percent total cations":"inorganics, major, metals",
	"endosulfan":"organics, pesticide",
	"phosphate-phosphorus as po4":"nutrient",
	"hydrocarbons":"organics, other",
	"hydroxide as calcium carbonate":"inorganics, major, non-metals",
	"simetone":"organics, pesticide",
	"dibenzothiophene":"organics, other",
	"xylene":"organics, other",
	"methyl isobutyl ketone":"organics, other",
	"arsenite":"inorganics, minor, non-metals",
	"dissolved sodium":"inorganics, major, metals",
	"camphor":"organics, pesticide",
	"polychlorinated biphenyls":"organics, pcbs",
	"hypochlorite ion":"inorganics, major, metals",
	"dissolved molybdenum":"inorganics, minor, metals",
	"endothall":"organics, pesticide",
	"organic nitrogen":"nutrient",
	"hexachloroethane":"organics, other",
	"dichloroethylene":"organics, other",
	"total mercury":"inorganics, minor, metals",
	"nitrite as n":"nutrient",
	"arsonic acid, methyl-, ion(1-)":"organics, other",
	"hydrocodone bitartrate":"organics, other",
	"uranium":"radiochemical",
	"silvex":"organics, pesticide",
	"neon":"inorganics, minor, non-metals",
	"p-(1,1,3,3-tetramethylbutyl)phenol":"organics, other",
	"chlorobenzene":"toxicity",
	"germanium":"inorganics, minor, non-metals",
	"specific gravity":"physical",
	"toxaphene":"organics, pesticide",
	"1,3-dichloropropylene, total":"organics, pesticide",
	"temperature, water":"physical",
	"silica":"inorganics, major, non-metals",
	"chlordecone":"organics, pesticide",
	"width":"information",
	"lasso":"information",
	"4-bromophenyl phenyl ether":"organics, other",
	"cfc-113":"organics, other",
	"fluometuron":"organics, pesticide",
	"diethyl phthalate":"organics, other",
	"thiobencarb":"organics, pesticide",
	"tin":"inorganics, minor, metals",
	"silver":"inorganics, minor, metals",
	"3,4-dichloroaniline":"organics, pesticide",
	"methyl acetate":"organics, other",
	"oil and grease -- cwa 304b":"organics, other",
	"simetryn":"organics, pesticide",
	"nitrogen-15/14 ratio":"stable isotopes",
	"2-ethylnaphthalene":"organics, other",
	"1,1,1,2-tetrachloroethane":"organics, other",
	"ethyl acetate":"organics, other",
	"beryllium":"inorganics, minor, metals",
	"methacrylonitrile":"organics, other",
	"ammonia as n":"nutrient",
	"nutrient-nitrogen":"nutrient",
	"cymene":"organics, other",
	"aroclor 1242":"organics, pcbs",
	"weather comments (text)":"information",
	"hexachlorocyclopentadiene":"organics, other",
	"alkalinity, phenolphthalein (total hydroxide+1/2 carbonate) as caco3":"inorganics, major, non-metals",
	"n-butylbenzene":"organics, other",
	"sodium plus potassium":"inorganics, major, metals",
	"desethylatrazine":"organics, pesticide",
	"aroclor 1248":"organics, pcbs",
	"caprolactam":"organics, other",
	"butyl benzyl phthalate":"organics, other",
	"n-nitrosodiphenylamine":"organics, other",
	"nitrate and nitrite as no3":"nutrient",
	"water level in well, depth from a reference point":"physical",
	"pentachloronitrobenzene":"organics, pesticide",
	"morphinan-6-one, 4,5-epoxy-14-hydroxy-3-methoxy-17-methyl-, (5.alpha.)-":"organics, other",
	"bismuth-214":"radiochemical",
	"precipitation":"physical",
	"depth, snow cover":"physical",
	"carbon-14":"radiochemical",
	"bismuth-212":"radiochemical",
	"p,p'-ddd":"organics, pesticide",
	"p,p'-dde":"organics, pesticide",
	"4h-cyclopenta[def]phenanthrene":"organics, other",
	"dimethyl phthalate":"organics, other",
	"ammonia and ammonium":"nutrient",
	"chlorophyll a, free of pheophytin":"biological",
	"cis-1,2-dichloroethylene":"organics, other",
	"m-chlorotoluene":"organics, other",
	"iridium":"inorganics, minor, metals",
	"isopropylbenzene":"organics, other",
	"p,p'-ddt":"organics, pesticide",
	"sulfate as so4":"inorganics, major, non-metals",
	"chloroprene":"organics, other",
	"no2+no3 as n":"nutrient",
	"tungsten":"inorganics, minor, metals",
	"odor, atmospheric":"physical",
	"percent sodium":"inorganics, major, metals",
	"true color":"physical",
	"fluoride":"inorganics, major, non-metals",
	"benzene":"toxicity",
	"2,2,4,5,6,7,8,8-octachloro-2,3,3a,4,7,7a-hexahydro-4,7-methano-1h-indene":"organics, pesticide",
	"rubidium":"inorganics, minor, metals",
	"ethinyl estradiol":"organics, other",
	"benzenemethanol, .alpha.-[(1s)-1-(methylamino)ethyl]-, (.alpha.s)-":"organics, other",
	"isodrin":"organics, pesticide",
	"p-chloroaniline":"organics, pesticide",
	"neburon":"organics, pesticide",
	"morphinan-6-ol, 7,8-didehydro-4,5-epoxy-3-methoxy-17-methyl-, (5.alpha.,6.alpha.)-":"organics, other",
	"ethoprop":"organics, pesticide",
	"dichloroacetic acid":"organics, other",
	"yttrium":"inorganics, minor, metals",
	"total zinc":"inorganics, minor, metals",
	"cyprazine":"organics, pesticide",
	"bhc-gamma":"organics, pesticide",
	"indole":"organics, other",
	"nitrate as n":"nutrient",
	"europium":"inorganics, minor, metals",
	"uranium-234 and/or uranium-235 and/or uranium-238":"radiochemical",
	"lead":"inorganics, minor, metals",
	"bromoxynil-13c6":"organics, pesticide",
	"acidity, total (caco3)":"inorganics, major, non-metals",
	"coliform/streptococcus ratio, fecal":"microbiological",
	"lutetium":"inorganics, minor, metals",
	"height, gage":"physical",
	"total arsenic":"inorganics, minor, non-metals",
	"cumene":"organics, other",
	"heterotrophic bacteria":"microbiological",
	"azoxystrobin":"organics, pesticide",
	"acridine":"organics, other",
	"atenolol":"organics, other",
	"cycloate":"organics, pesticide",
	"wind direction (direction from, expressed 0-360 deg)":"physical",
	"dimethenamid oa":"organics, pesticide",
	"carbamazepine-d10":"organics, other",
	"1,1,1-trichloro-2-propanone":"organics, other",
	"stigmast-5-en-3-ol, (3.beta.)-":"organics, other",
	"isophorone":"organics, other",
	"musk ketone":"organics, other",
	"radium-226":"radiochemical",
	".lambda.-cyhalothrin":"organics, pesticide",
	"butane, 1-chloro-":"organics, other",
	"o-dichlorobenzene":"organics, other",
	"metolachlor esa":"organics, pesticide",
	"benzene, 1,3(and 1,4)-dimethyl- chemical m(and p)-xylene":"organics, other",
	"calcium as caco3":"inorganics, major, metals",
	"isoquinoline":"organics, other",
	"alkalinity as cac03":"inorganics, major, non-metals",
	"atrazine-d5 (ethyl-d5)":"organics, pesticide",
	"fecal coliform":"microbiological",
	"3,5-dichloroaniline":"organics, pesticide",
	"1h-benzotriazole, 5-methyl-":"organics, other",
	"estrone":"organics, other",
	"vanadium, total":"inorganics, minor, metals",
	"phosphorus, soluble":"nutrient",
	"p-xylene":"organics, other",
	"tin, total":"inorganics, minor, metals",
	"4,4'-isopropylidenediphenol":"organics, other",
	"bis(2-ethylhexyl) phthalate":"organics, other",
	"chlordane, technical":"organics, pesticide",
	"indium":"inorganics, minor, metals",
	"gallium":"inorganics, minor, metals",
	"ethyl methacrylate":"organics, other",
	"trans-nonachlor":"organics, pesticide",
	"gasoline range organics":"organics, other",
	"dibenzo(a,h)anthracene":"organics, other",
	"total dissolved solids":"physical",
	"dimethenamid":"organics, pesticide",
	"allyl chloride":"organics, pesticide",
	"paraoxon":"organics, pesticide",
	"europium-152":"radiochemical",
	"t. alk/caco3":"inorganics, major, non-metals",
	"endosulfan sulfate":"organics, pesticide",
	"imazaquin":"organics, pesticide",
	"actinium-228":"radiochemical",
	"benzophenone":"organics, other",
	"phosphate, total":"nutrient",
	"ethyl alcohol":"organics, other",
	"manganese, suspended":"inorganics, minor, metals",
	"temazepam":"organics, other",
	"diuron metabolite":"organics, pesticide",
	"1,2,3,4-tetramethylbenzene":"organics, other",
	"butachlor":"organics, pesticide",
	"1rs cis-permethrin":"organics, pesticide",
	"perchlorate":"inorganics, minor, non-metals",
	"1,2,3-trimethylbenzene":"organics, other",
	"dissolved oxygen saturation":"inorganics, major, non-metals",
	"thallium-208":"radiochemical",
	"carbaryl":"organics, pesticide",
	"benzene, 1-methoxy-2-[2,2,2-trichloro-1-(4-methoxyphenyl)ethyl]-":"organics, pesticide",
	"phosmet":"organics, pesticide",
	"2,3,4-trichlorobiphenyl":"organics, pcbs",
	"dibutyl phthalate":"organics, other",
	"altitude":"information",
	"oxygen-18/oxygen-16 ratio":"stable isotopes",
	"bromoacetic acid":"organics, other",
	"nicosulfuron":"organics, pesticide",
	"bromide":"inorganics, major, non-metals",
	"o,p'-ddt":"organics, pesticide",
	"1,2,3-trichloropropane":"information",
	"norfluoxetine oxalate":"organics, other",
	"trans-chlordane":"organics, pesticide",
	"dichlobenil":"organics, pesticide",
	"combined radium (-226 & -228)":"radiochemical",
	"phosphorus as p":"nutrient",
	"turbidity, hellige":"physical",
	"1,1-dichloroethane":"organics, other",
	"benzoylecgonine hydrate":"organics, other",
	"2,4-dinitrotoluene":"organics, other",
	"dieldrin":"organics, pesticide",
	"indeno[1,2,3-cd]pyrene":"organics, other",
	"norflurazon":"organics, pesticide",
	"dissolved copper":"inorganics, minor, metals",
	"p-nitrophenol":"organics, pesticide",
	"2,6-dinitrotoluene":"organics, other",
	"gemfibrozil-d6":"organics, other",
	"triamterene":"organics, other",
	"p-cymene":"organics, other",
	"hydrocodone-d6":"organics, other",
	"ethanone, 1-(2,3-dihydro-1,1,2,3,3,6-hexamethyl-1h-inden-5-yl)-":"organics, other",
	"gross alpha, incl. radon & u":"radiochemical",
	"linuron":"organics, pesticide",
	"benzeneethanamine, .alpha.-methyl-, (.alpha.s)-, sulfate (2:1)":"organics, other",
	"temperature, sample":"physical",
	"tert-butanol":"organics, other",
	".beta.-bhc":"organics, pesticide",
	"nitrate-nitrite":"nutrient",
	"acidity, hydrogen ion (h+) as caco3":"inorganics, major, non-metals",
	"1,3-butadiene":"organics, pesticide",
	"prowl":"organics, pesticide",
	"alkalinity, bicarbonate":"inorganics, major, non-metals",
	"mcpa":"organics, pesticide",
	"mcpb":"organics, pesticide",
	"phosphate":"nutrient",
	"dissolved nitrite: no2":"nutrient",
	"ethalfluralin":"organics, pesticide",
	"thimet":"organics, pesticide",
	"trans-1,2-dichloroethylene":"organics, other",
	"carbon-13/carbon-12, ratio":"stable isotopes",
	"dissolved oxygen (field)":"inorganics, major, non-metals",
	"napropamide":"organics, pesticide",
	".beta.-hexachlorocyclohexane":"organics, pesticide",
	"hardness, carbonate as caco3":"physical",
	"dibromochloromethane":"organics, other",
	"acidity":"inorganics, major, non-metals",
	"trichlorofluoromethane":"organics, other",
	"chloroneb":"organics, pesticide",
	"enterococcus":"microbiological",
	"cloud cover (percent)":"physical",
	"o,p'-dde":"organics, pesticide",
	"chlordane":"organics, pesticide",
	"total hardness -- sdwa npdwr":"physical",
	"dibenzofuran":"organics, other",
	"odor threshold number":"physical",
	"tribufos":"organics, pesticide",
	"nickel":"inorganics, minor, metals",
	"chlorinated naphthalenes":"organics, other",
	"disulfoton":"organics, pesticide",
	"cyclohexene, 1-methyl-4-(1-methylethenyl)-, (4r)-":"organics, other",
	"alkalinity, phenolphthalein":"inorganics, major, non-metals",
	"2-(dimethylamino)-n-hydroxy-2-oxoethanimidothioic acid methyl ester":"organics, pesticide",
	"methylmercury(1+)":"organics, other",
	"carisoprodol":"organics, other",
	"ethylan":"organics, pesticide",
	"beta, dissolved":"radiochemical",
	"sulfur-34/sulfur-32, ratio":"stable isotopes",
	"volume storage":"information",
	"vinyl chloride":"toxicity",
	"5-amino-1-[2,6-dichloro-4-(trifluoromethyl)phenyl]-4-[(trifluoromethyl)thio]pyrazole-3-carbonitrile":"organics, pesticide",
	"copper summary":"inorganics, minor, metals",
	"ortho. phosphate":"nutrient",
	"cesium-137":"radiochemical",
	"fipronil":"organics, pesticide",
	"particle size, sieve no. 230, 250 mesh, (0.063mm)":"sediment",
	"cesium-134":"radiochemical",
	"phenol":"organics, other",
	"acetaminophen":"organics, other",
	"trifluralin":"organics, pesticide",
	"1,2-dichloroethylene":"organics, other",
	"total phosphorus":"nutrient",
	"kjeldahl nitrogen":"nutrient",
	"benzaldehyde":"organics, other",
	"depth to water level below land surface":"physical",
	"cyclohexane":"organics, other",
	"alkalinity, carbonate as caco3":"inorganics, major, non-metals",
	"total cadmium":"inorganics, minor, metals",
	"pcb 1262":"organics, pcbs",
	"acidity, hydrogen ion (h+)":"inorganics, major, non-metals",
	"water content of snow":"physical",
	"m-dinitrobenzene":"organics, other",
	"temperature (centigrade)":"physical",
	"tris(1,3-dichloro-2-propyl)phosphate":"organics, other",
	"ammonium":"nutrient",
	"silica, dis. si02":"inorganics, major, non-metals",
	"dichlorobromomethane":"organics, other",
	"heptachlor":"organics, pesticide",
	"2-chloronaphthalene":"organics, other",
	"ethion monooxon":"organics, pesticide",
	"arsenate (aso43-)":"inorganics, minor, non-metals",
	"cis-nonachlor":"organics, pesticide",
	"plutonium-239 and plutonium-240 combined":"radiochemical",
	"phosphorus":"nutrient",
	"lead-210":"radiochemical",
	"hardness, total (as caco3)":"physical",
	"bis(2-chloroisopropyl) ether":"organics, other",
	"1,4-benzenedicarboxylic acid, 2,3,5,6-tetrachloro-, monomethyl ester":"organics, pesticide",
	"lead-214":"radiochemical",
	"temperature, air":"physical",
	"alprazolam-d5":"organics, other",
	"methyl alcohol":"organics, other",
	"estra-1,3,5,7,9-pentaen-17-one, 3-hydroxy-":"organics, other",
	"benzo(a)pyrene":"organics, other",
	"carbofuran":"organics, pesticide",
	"chromium, hex":"inorganics, minor, metals",
	"dimethachlor":"organics, pesticide",
	"fluoranthene":"organics, other",
	"palladium":"inorganics, minor, metals",
	"1,2-dichloropropane":"organics, pesticide",
	"bromacil":"information",
	"ethyl ether":"organics, other",
	"silica d/sio2":"inorganics, major, non-metals",
}
