#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
paramGroups.py
------------------------------------
parameter group to fill in ParamGroup
'''

param_groups = {'carbonate as co3': 'inorganics, major, non-metals',
                'benzo(g,h,i)perylene': 'organics, other',
                'n-nitrosodimethylamine': 'organics, other',
                '2,4-d': 'organics, pesticide',
                'bromobenzene': 'organics, other',
                'cobalt': 'inorganics, minor, metals',
                'methyl ethyl ketone': 'organics, other',
                'zinc': 'inorganics, minor, metals',
                'dissolved calcium': 'inorganics, major, metals',
                'butylate': 'organics, pesticide',
                'ammonia': 'nutrient',
                'orthophosphate': 'nutrient',
                '1,1,2,2-tetrachloroethane': 'organics, other',
                '2-nitroaniline': 'organics, other',
                'manganese, dissolved': 'inorganics, minor, metals',
                'alpha, dissolved': 'radiochemical',
                'dichlorvos': 'organics, pesticide',
                'propachlor': 'organics, pesticide',
                'barium': 'inorganics, minor, metals',
                'cis-1,3-dichloropropene': 'organics, pesticide',
                '2-chloro-4-isopropylamino-6-amino-s-triazine': 'organics, pesticide',
                'trans-1,2-dichloroethylene': 'organics, other',
                'inorganic carbon': 'inorganics, major, non-metals',
                'di(2-ethylhexyl) phthalate': 'organics, other',
                'methyl bromide': 'organics, pesticide',
                'di-n-butyl phthalate': 'organics, other',
                'bis(2-chloroethoxy)methane': 'organics, other',
                'n-hexane': 'organics, other',
                'p-dichlorobenzene': 'organics, pesticide',
                'p-nitroaniline': 'organics, other',
                'alkalinity, hydroxide as caco3': 'inorganics, major, non-metals',
                'antimony, total': 'inorganics, minor, non-metals',
                'methane': 'organics, other',
                'metribuzin': 'organics, pesticide',
                'dissolved zinc': 'inorganics, minor, metals',
                'total chlorine': 'inorganics, major, non-metals',
                '1,3,5-trimethylbenzene': 'organics, other',
                'sulfide': 'inorganics, major, non-metals',
                '1,1-dichloroethylene': 'organics, other',
                'copper, free': 'inorganics, minor, metals',
                'ethylene glycol': 'organics, other',
                'oxamyl': 'organics, pesticide',
                '2-methylphenol': 'organics, pesticide',
                '1-butanol': 'organics, other',
                'thimet': 'organics, pesticide',
                'carbon tetrachloride': 'organics, other',
                'phosphate, reactive': 'nutrient',
                'propazine': 'organics, pesticide',
                '2-chloroethyl vinyl ether': 'organics, other',
                'benzo[ghi]perylene': 'organics, other',
                'dichlorodifluoromethane': 'organics, other',
                'chlorate': 'inorganics, minor, non-metals',
                'phosphorus, total': 'nutrient',
                '1,1,2-trichloroethane': 'organics, other',
                'strontium': 'inorganics, minor, metals',
                'benzoic acid': 'organics, other',
                'titanium, total': 'inorganics, minor, metals',
                'ethanol': 'organics, other',
                'boron': 'inorganics, minor, non-metals',
                'benzo(b)fluoranthene': 'organics, other',
                '1,3-dichloropropene': 'organics, pesticide',
                'simazine': 'organics, pesticide',
                'cesium': 'inorganics, minor, metals',
                'bis(chloromethyl) ether': 'organics, other',
                'organic nitrogen': 'nutrient',
                "3,3'-dichlorobenzidine": 'organics, other',
                'hexachlorobutadiene': 'organics, other',
                'phosphorus 0 as p': 'nutrient',
                '4-nitroaniline': 'organics, other',
                'sulfate': 'inorganics, major, non-metals',
                'ammonia as nh3': 'nutrient',
                'acidity, m.o. (caco3)': 'inorganics, major, non-metals',
                'acetochlor': 'organics, pesticide',
                'nitrate as n': 'nutrient',
                'total polychlorinated biphenyls (pcb)': 'organics, pcbs',
                'm-nitroaniline': 'organics, other',
                '1,1,1-trichloroethane': 'organics, other',
                'molinate': 'organics, pesticide',
                'niobium': 'inorganics, minor, metals',
                '3-hydroxycarbofuran': 'organics, pesticide',
                'phorate': 'organics, pesticide',
                'chloride': 'inorganics, major, non-metals',
                'benzo(k)fluoranthene': 'organics, other',
                'phenanthrene': 'organics, other',
                'iodide': 'inorganics, minor, non-metals',
                'ethyl acetate': 'organics, other',
                'total cadmium': 'inorganics, minor, metals',
                'paraquat': 'organics, pesticide',
                'total zinc': 'inorganics, minor, metals',
                'dimethoate': 'organics, pesticide',
                'hexane': 'organics, other',
                'di-n-octyl phthalate': 'organics, other',
                'zirconium': 'inorganics, minor, metals',
                'carbon, total': 'inorganics, major, non-metals',
                'dissolved selenium': 'inorganics, minor, non-metals',
                'permethrin': 'organics, pesticide',
                '2,4,6-trichlorophenol': 'organics, pesticide',
                'dissolved nitrate: no3': 'nutrient',
                'methomyl': 'organics, pesticide',
                'p-cresol': 'organics, pesticide',
                'aniline': 'organics, other',
                'dysprosium': 'inorganics, minor, metals',
                'fluorene': 'organics, other',
                'dinoseb': 'organics, pesticide',
                'titanium': 'inorganics, minor, metals',
                'parathion (ethyl)': 'organics, pesticide',
                'p-chloro-m-cresol': 'organics, pesticide',
                'total sodium': 'inorganics, major, metals',
                'cfc-12': 'organics, other',
                'diuron': 'organics, pesticide',
                'cfc-11': 'organics, other',
                'hydrogen': 'inorganics, major, non-metals',
                'bromoxynil': 'organics, pesticide',
                'beta, suspended': 'radiochemical',
                'o-cresol': 'organics, pesticide',
                'thallium': 'inorganics, minor, metals',
                'helium': 'inorganics, minor, non-metals',
                '2-chlorophenol': 'organics, other',
                'bismuth, total': 'inorganics, minor, metals',
                'dissolved lead': 'inorganics, minor, metals',
                'methanol': 'organics, other',
                '1,2,3-trimethylbenzene': 'organics, other',
                'orthophosphate as p': 'nutrient',
                'inorganic nitrogen (nitrate and nitrite)': 'nutrient',
                'methylene chloride': 'organics, other',
                'nitrobenzene': 'organics, other',
                'cadmium': 'inorganics, minor, metals',
                'scandium': 'inorganics, minor, metals',
                'm-dichlorobenzene': 'organics, other',
                'vanadium': 'inorganics, minor, metals',
                'bromodichloromethane': 'organics, other',
                'lindane': 'organics, pesticide',
                'manganese': 'inorganics, minor, metals',
                'toxaphene': 'organics, pesticide',
                'nitrogen, mixed forms (nh3), (nh4), organic, (no2) and (no3)': 'nutrient',
                'sutan': 'organics, pesticide',
                '4-methyl-2-pentanone': 'organics, other',
                'chromium, hex, as cr': 'inorganics, minor, metals',
                'phosphate-phosphorus': 'nutrient',
                'nitrogen': 'nutrient',
                'bentazon': 'organics, pesticide',
                'endrin': 'organics, pesticide',
                'neodymium': 'inorganics, minor, metals',
                'chlorpyrifos': 'organics, pesticide',
                'sodium': 'inorganics, major, metals',
                'hydrogen ion': 'inorganics, major, non-metals',
                'selenium': 'inorganics, minor, non-metals',
                'ammonium as n': 'nutrient',
                'guthion': 'organics, pesticide',
                '1,2-dibromo-3-chloropropane': 'organics, pesticide',
                'bromomethane': 'organics, pesticide',
                'chromium(vi)': 'inorganics, minor, metals',
                'free residual chlorine': 'inorganics, major, non-metals',
                'alkalinity': 'inorganics, major, non-metals',
                'alachlor esa': 'organics, pesticide',
                'dissolved arsenic': 'inorganics, minor, non-metals',
                'hexachlorobenzene': 'organics, pesticide',
                'silver': 'inorganics, minor, metals',
                'acetone': 'organics, other',
                'alpha particle': 'radiochemical',
                'molybdenum': 'inorganics, minor, metals',
                'oxygen': 'inorganics, major, non-metals',
                'praseodymium': 'inorganics, minor, metals',
                'ethylene dibromide': 'organics, pesticide',
                'dichloroacetonitrile': 'organics, other',
                '2,4,5-trichlorophenol': 'organics, pesticide',
                'hydroxide': 'inorganics, major, non-metals',
                'total nickel': 'inorganics, minor, metals',
                'carbon dioxide': 'inorganics, major, non-metals',
                'nitrite': 'nutrient',
                'acenaphthene': 'organics, other',
                's-ethyl dipropylthiocarbamate': 'organics, pesticide',
                'aldrin': 'organics, pesticide',
                'parathion': 'organics, pesticide',
                'dissolved chromium': 'inorganics, minor, metals',
                'fluorine': 'inorganics, major, non-metals',
                'acrylamide': 'organics, other',
                'alkalinity, phenolphthalein (total hydroxide+1/2 carbonate)': 'inorganics, major, non-metals',
                'spectracide': 'organics, pesticide',
                'chlorine dioxide': 'inorganics, major, non-metals',
                'bicarbonate': 'inorganics, major, non-metals',
                '2,4-dinitrophenol': 'organics, other',
                'ideno(1,2,3-cd)pyrene': 'organics, other',
                'alpha, suspended': 'radiochemical',
                '2,3,7,8-tcdd': 'organics, other',
                'chlorine': 'inorganics, major, non-metals',
                'residual chlorine': 'inorganics, major, non-metals',
                'lead summary': 'inorganics, minor, metals',
                'total boron': 'inorganics, minor, non-metals',
                'nitrogen-ammonia as (n)': 'nutrient',
                'silicon': 'inorganics, major, non-metals',
                'total manganese': 'inorganics, minor, metals',
                'dissolved boron': 'inorganics, minor, non-metals',
                'dibutyl phthalate': 'organics, other',
                'cyanide': 'inorganics, minor, non-metals',
                'isobutyl alcohol': 'organics, other',
                't. alk/caco3': 'inorganics, major, non-metals',
                'copper': 'inorganics, minor, metals',
                'dissolved oxygen (do)': 'inorganics, major, non-metals',
                'p-bromophenyl phenyl ether': 'organics, other',
                '2,4,5-t': 'organics, pesticide',
                '2-nitrophenol': 'organics, other',
                'alkalinity, caco3 stability': 'inorganics, major, non-metals',
                'total calcium': 'inorganics, major, metals',
                'o-nitrophenol': 'organics, other',
                'mercury': 'inorganics, minor, metals',
                'tetrachloroethylene': 'organics, other',
                'aldicarb sulfoxide': 'organics, pesticide',
                'isobutanol': 'organics, other',
                'carbonate': 'inorganics, major, non-metals',
                'phosphate, tot. dig. (as p)': 'nutrient',
                'thulium': 'inorganics, minor, metals',
                'baygon': 'organics, pesticide',
                'benzidine': 'organics, other',
                'aroclor 1262': 'organics, pcbs',
                'argon': 'inorganics, minor, non-metals',
                'dissolved manganese': 'inorganics, minor, metals',
                'formaldehyde': 'organics, other',
                'total carbon': 'inorganics, major, non-metals',
                'heptachlor epoxide': 'organics, pesticide',
                'boron, total': 'inorganics, minor, non-metals',
                'o-chlorophenol': 'organics, other',
                'bismuth': 'inorganics, minor, metals',
                'total barium': 'inorganics, minor, metals',
                'erbium': 'inorganics, minor, metals',
                'benz[a]anthracene': 'organics, other',
                '4,6-dinitro-o-cresol': 'organics, pesticide',
                'aldicarb': 'organics, pesticide',
                'magnesium': 'inorganics, major, metals',
                'iron': 'inorganics, minor, metals',
                'des-isopropyl-atrazine': 'organics, pesticide',
                '2,4-dimethylphenol': 'organics, pesticide',
                'mecoprop': 'organics, pesticide',
                'methoxychlor': 'organics, pesticide',
                'pendimethalin': 'organics, pesticide',
                '4-chlorophenyl phenyl ether': 'organics, other',
                'dicamba': 'organics, pesticide',
                'dissolved cadmium': 'inorganics, minor, metals',
                'malathion': 'organics, pesticide',
                'dissolved magnesium': 'inorganics, major, metals',
                'total aluminum': 'inorganics, minor, metals',
                'chlorodibromomethane': 'organics, other',
                'cis-chlordane': 'organics, pesticide',
                'methyl tert-butyl ether': 'organics, other',
                '3-nitroaniline': 'organics, other',
                'polychlorinated biphenyls': 'organics, pcbs',
                'arsenite': 'inorganics, minor, non-metals',
                'chloromethane': 'organics, other',
                '2-chloro-6-ethylamino-4-amino-s-triazine': 'organics, pesticide',
                '2-methyl-4,6-dinitrophenol': 'organics, pesticide',
                'glyphosate': 'organics, pesticide',
                'potassium': 'inorganics, major, metals',
                'nitrate-nitrogen': 'nutrient',
                'alachlor': 'organics, pesticide',
                '1,2-dichloroethane': 'organics, pesticide',
                'bicarbonate as caco3': 'inorganics, major, non-metals',
                'bromoform': 'organics, other',
                'nitrite as n': 'nutrient',
                'dalapon': 'organics, pesticide',
                'acetaldehyde': 'organics, other',
                'alpha-chlordane': 'organics, pesticide',
                '1,4-dioxane': 'organics, other',
                'carbonate as caco3': 'inorganics, major, non-metals',
                'total magnesium': 'inorganics, major, metals',
                'dissolved potassium': 'inorganics, major, metals',
                'dissolved nitrite: no2': 'nutrient',
                'carbonate (co3)': 'inorganics, major, non-metals',
                'tellurium': 'inorganics, minor, non-metals',
                'sodium adsorption ratio': 'inorganics, major, metals',
                'total copper': 'inorganics, minor, metals',
                'iron, dissolved': 'inorganics, minor, metals',
                'chloral hydrate': 'organics, other',
                'gadolinium': 'inorganics, minor, metals',
                'acrylonitrile': 'organics, pesticide',
                'nitrogen, ammonium/ammonia ratio': 'nutrient',
                'chloroethane': 'organics, other',
                'beryllium, total': 'inorganics, minor, metals',
                'gross beta particle activity': 'radiochemical',
                'xylenes, total': 'organics, other',
                'total kjeldahl nitrogen (in water mg/l)': 'nutrient',
                'sulfur': 'inorganics, major, non-metals',
                '2,4,5-tp': 'organics, pesticide',
                'asbestos': 'inorganics, minor, non-metals',
                'cyanides amenable to chlorination (hcn & cn)': 'inorganics, minor, non-metals',
                'combined uranium': 'radiochemical',
                'cerium': 'inorganics, minor, metals',
                'para-para ddd': 'organics, pesticide',
                'para-para dde': 'organics, pesticide',
                'iron, ion (fe2+)': 'inorganics, minor, metals',
                'lithium, total': 'inorganics, minor, metals',
                '2-methylnaphthalene': 'organics, other',
                'alkalinity, carbonate': 'inorganics, major, non-metals',
                'tungsten': 'inorganics, minor, metals',
                'para-para ddt': 'organics, pesticide',
                'azinphos-methyl': 'organics, pesticide',
                'terbium': 'inorganics, minor, metals',
                'aluminum': 'inorganics, minor, metals',
                'total iron': 'inorganics, minor, metals',
                'ammonia-nitrogen': 'nutrient',
                'alkalinity, total as caco3': 'inorganics, major, non-metals',
                'benzo[a]pyrene': 'organics, other',
                't.k.n.': 'nutrient',
                'total alkalinity as caco3': 'inorganics, major, non-metals',
                'beta particle': 'radiochemical',
                'hcfc-22': 'organics, other',
                'alkalinity, total': 'inorganics, major, non-metals',
                'n-propylbenzene': 'organics, other',
                'antimony': 'inorganics, minor, non-metals',
                'chromium(iii)': 'inorganics, minor, metals',
                '2,4-dichlorophenol': 'organics, pesticide',
                'ammonia-nitrogen as n': 'nutrient',
                'dichloroiodomethane': 'organics, other',
                'di(2-ethylhexyl) adipate': 'organics, other',
                'p-chlorophenyl phenyl ether': 'organics, other',
                'aldicarb sulfone': 'organics, pesticide',
                '4-chloroaniline': 'organics, pesticide',
                'diazinon': 'organics, pesticide',
                'samarium': 'inorganics, minor, metals',
                'o-nitroaniline': 'organics, other',
                'metolachlor': 'organics, pesticide',
                'naphthalene': 'organics, other',
                '4-nitrophenol': 'organics, pesticide',
                'gross alpha particle activity': 'radiochemical',
                'bromine': 'inorganics, minor, non-metals',
                'dissolved oxygen (field)': 'inorganics, major, non-metals',
                'trichloroacetic acid': 'organics, other',
                'hydrogen sulfide': 'inorganics, major, non-metals',
                'trichloroethylene': 'organics, other',
                '2,3,7,8-tetrachlorodibenzo-p-dioxin': 'organics, other',
                'dibenz[a,h]anthracene': 'organics, other',
                'uranium-238': 'radiochemical',
                'bis(2-chloroethyl) ether': 'organics, other',
                '2,4-db': 'organics, pesticide',
                'cyanazine': 'organics, pesticide',
                '1,2,4-trichlorobenzene': 'organics, other',
                'arsenic': 'inorganics, minor, non-metals',
                'chromium': 'inorganics, minor, metals',
                'rhenium': 'inorganics, minor, metals',
                'methyl methacrylate': 'organics, other',
                'sulfur hexafluoride': 'inorganics, minor, non-metals',
                'total molybdenum': 'inorganics, minor, metals',
                'perchlorate': 'inorganics, minor, non-metals',
                'dissolved iron': 'inorganics, minor, metals',
                '.alpha.-hexachlorocyclohexane': 'organics, pesticide',
                'dichlorovos': 'organics, pesticide',
                '1,2,4-trimethylbenzene': 'organics, other',
                'prometon': 'organics, pesticide',
                'chlorodifluoromethane (hcfc-22)': 'organics, other',
                'dichloromethane': 'organics, other',
                'chlorite': 'inorganics, major, non-metals',
                'acrolein': 'organics, other',
                '3,3-dichlorobenzidine': 'organics, other',
                'carbon disulfide': 'organics, pesticide',
                'propoxur': 'organics, pesticide',
                'n-butyl alcohol': 'organics, other',
                'ytterbium': 'inorganics, minor, metals',
                'benzyl alcohol': 'organics, other',
                'hexachloroethane': 'organics, other',
                'anthracene': 'organics, other',
                'azobenzene': 'organics, pesticide',
                'dichlorprop': 'organics, pesticide',
                'lanthanum': 'inorganics, minor, metals',
                'tert-butylbenzene': 'organics, other',
                'dibromoacetonitrile': 'organics, other',
                'acidity as caco3': 'inorganics, major, non-metals',
                'calcium': 'inorganics, major, metals',
                'dissolved nickel': 'inorganics, minor, metals',
                'bicarbonate as hco3': 'inorganics, major, non-metals',
                'ammonia as n': 'nutrient',
                'chlorthal-dimethyl': 'organics, pesticide',
                'sec-butylbenzene': 'organics, other',
                'total potassium': 'inorganics, major, metals',
                'total chromium': 'inorganics, minor, metals',
                'molybdenum, total': 'inorganics, minor, metals',
                'eptc': 'organics, pesticide',
                'o-xylene': 'organics, other',
                'acenaphthylene': 'organics, other',
                'dissolved mercury': 'inorganics, minor, metals',
                'butylbenzyl phthalate': 'organics, other',
                'radium-226': 'radiochemical',
                'radium-228': 'radiochemical',
                'dcpa': 'organics, pesticide',
                'm-xylene': 'organics, other',
                'holmium': 'inorganics, minor, metals',
                'lithium': 'inorganics, minor, metals',
                'ethylbenzene': 'organics, other',
                '4-methylphenol': 'organics, pesticide',
                'permethrin (mixed, cis, trans)': 'organics, pesticide',
                'gran acid neutralizing capacity': 'inorganics, major, non-metals',
                'chloroform': 'organics, other',
                '.alpha.-bhc': 'organics, pesticide',
                'chloropyrifos': 'organics, pesticide',
                'n-nitrosodi-n-propylamine': 'organics, other',
                'benzo(a)anthracene': 'organics, other',
                '2-hexanone': 'organics, other',
                'benzo[k]fluoranthene': 'organics, other',
                'sodium, percent total cations': 'inorganics, major, metals',
                'phosphate-phosphorus as po4': 'nutrient',
                'krypton': 'inorganics, minor, non-metals',
                'hydroxide as calcium carbonate': 'inorganics, major, non-metals',
                'xylene': 'organics, other',
                'p-nitrophenol': 'organics, pesticide',
                'dissolved barium': 'inorganics, minor, metals',
                'dissolved sodium': 'inorganics, major, metals',
                'hypochlorite ion': 'inorganics, major, metals',
                'dissolved molybdenum': 'inorganics, minor, metals',
                'endothall': 'organics, pesticide',
                'total mercury': 'inorganics, minor, metals',
                'total selenium': 'inorganics, minor, non-metals',
                'silvex': 'organics, pesticide',
                'neon': 'inorganics, minor, non-metals',
                'chlorobenzene': 'organics, other',
                'germanium': 'inorganics, minor, non-metals',
                '1,3-dichloropropylene, total': 'organics, pesticide',
                'lasso': 'organics, pesticide',
                '4-bromophenyl phenyl ether': 'organics, other',
                'acetic acid': 'organics, other',
                'methyl acetate': 'organics, other',
                'toluene': 'organics, other',
                'beryllium': 'inorganics, minor, metals',
                'atrazine': 'organics, pesticide',
                'hexachlorocyclopentadiene': 'organics, other',
                'n-butylbenzene': 'organics, other',
                'sodium plus potassium': 'inorganics, major, metals',
                'desethylatrazine': 'organics, pesticide',
                'butyl benzyl phthalate': 'organics, other',
                'n-nitrosodiphenylamine': 'organics, other',
                'pyrene': 'organics, other',
                "p,p'-ddd": 'organics, pesticide',
                "p,p'-dde": 'organics, pesticide',
                'dimethyl phthalate': 'organics, other',
                'ammonia and ammonium': 'nutrient',
                'thallium, total': 'inorganics, minor, metals',
                'cis-1,2-dichloroethylene': 'organics, other',
                'alkalinity, bicarbonate as caco3': 'inorganics, major, non-metals',
                'tribromomethane': 'organics, other',
                'isopropylbenzene': 'organics, other',
                'nitrate + nitrite as n': 'nutrient',
                "p,p'-ddt": 'organics, pesticide',
                'inorganic nitrogen (nitrate and nitrite) as n': 'nutrient',
                'total lead': 'inorganics, minor, metals',
                'percent sodium': 'inorganics, major, metals',
                'fluoride': 'inorganics, major, non-metals',
                'benzene': 'organics, other',
                'no2+no3 as n': 'nutrient',
                'rubidium': 'inorganics, minor, metals',
                'p-chloroaniline': 'organics, pesticide',
                'gross alpha, incl. radon & u': 'radiochemical',
                'dichloroacetic acid': 'organics, other',
                'bhc-gamma': 'organics, pesticide',
                'europium': 'inorganics, minor, metals',
                'uranium-234 and/or uranium-235 and/or uranium-238': 'radiochemical',
                'lead': 'inorganics, minor, metals',
                'fluoranthene': 'organics, other',
                'lutetium': 'inorganics, minor, metals',
                'total arsenic': 'inorganics, minor, non-metals',
                'cumene': 'organics, other',
                'nitrate': 'nutrient',
                'isophorone': 'organics, other',
                'yttrium': 'inorganics, minor, metals',
                'butane, 1-chloro-': 'organics, other',
                'methyl isobutyl ketone': 'organics, other',
                'alkalinity as cac03': 'inorganics, major, non-metals',
                'chrysene': 'organics, other',
                'vanadium, total': 'inorganics, minor, metals',
                'phosphorus, soluble': 'nutrient',
                'p-xylene': 'organics, other',
                'tin, total': 'inorganics, minor, metals',
                'cobalt, total': 'inorganics, minor, metals',
                'bis(2-ethylhexyl) phthalate': 'organics, other',
                'gallium': 'inorganics, minor, metals',
                'ethyl methacrylate': 'organics, other',
                'dibenzo(a,h)anthracene': 'organics, other',
                'trans-1,3-dichloropropene': 'organics, pesticide',
                'prometryn': 'organics, pesticide',
                'diethyl phthalate': 'organics, other',
                'phosphate, total': 'nutrient',
                'ethyl alcohol': 'organics, other',
                'manganese, suspended': 'inorganics, minor, metals',
                'butachlor': 'organics, pesticide',
                'o-chlorotoluene': 'organics, other',
                'dissolved oxygen saturation': 'inorganics, major, non-metals',
                'carbaryl': 'organics, pesticide',
                'styrene': 'organics, other',
                'bromide': 'inorganics, major, non-metals',
                '1,2,3-trichloropropane': 'organics, pesticide',
                '1,1-dichloroethane': 'organics, other',
                '2,4-dinitrotoluene': 'organics, other',
                'dieldrin': 'organics, pesticide',
                'indeno[1,2,3-cd]pyrene': 'organics, other',
                'dissolved copper': 'inorganics, minor, metals',
                '2,6-dinitrotoluene': 'organics, other',
                'total iron-d max, dmr': 'inorganics, minor, metals',
                '.beta.-bhc': 'organics, pesticide',
                'nitrate-nitrite': 'nutrient',
                'combined chlorine': 'inorganics, major, non-metals',
                '1,3-butadiene': 'organics, pesticide',
                'prowl': 'organics, pesticide',
                'alkalinity, bicarbonate': 'inorganics, major, non-metals',
                'mcpa': 'organics, pesticide',
                'phosphate': 'nutrient',
                'vinyl acetate': 'organics, other',
                '1-chlorobutane': 'organics, other',
                'tebuthiuron': 'organics, pesticide',
                'sodium adsorption ratio [(na)/(sq root of 1/2 ca + mg)]': 'inorganics, major, metals',
                '.beta.-hexachlorocyclohexane': 'organics, pesticide',
                'dibromochloromethane': 'organics, other',
                'trichlorofluoromethane': 'organics, other',
                'phosphate-phosphorus as p': 'nutrient',
                'dibenzofuran': 'organics, other',
                'nickel': 'inorganics, minor, metals',
                'terbufos': 'organics, pesticide',
                'alkalinity, phenolphthalein': 'inorganics, major, non-metals',
                'dissolved aluminum': 'inorganics, minor, metals',
                'beta, dissolved': 'radiochemical',
                'vinyl chloride': 'organics, other',
                'nan': 'radiochemical',
                'copper summary': 'inorganics, minor, metals',
                'ortho. phosphate': 'nutrient',
                'tin': 'inorganics, minor, metals',
                'ethanoic acid': 'organics, other',
                'trifluralin': 'organics, pesticide',
                'total phosphorus': 'nutrient',
                'kjeldahl nitrogen': 'nutrient',
                'alkalinity, carbonate as caco3': 'inorganics, major, non-metals',
                'pcb 1262': 'organics, pcbs',
                'xenon': 'inorganics, minor, non-metals',
                'o-dichlorobenzene': 'organics, other',
                'ammonium': 'nutrient',
                'silica, dis. si02': 'inorganics, major, non-metals',
                'dichlorobromomethane': 'organics, other',
                'heptachlor': 'organics, pesticide',
                '2-chloronaphthalene': 'organics, other',
                'arsenate (aso43-)': 'inorganics, minor, non-metals',
                'vinyl 2-chloroethyl ether': 'organics, other',
                'phosphorus': 'nutrient',
                'iron, suspended': 'inorganics, minor, metals',
                'silica': 'inorganics, major, non-metals',
                'methyl alcohol': 'organics, other',
                'benzo(a)pyrene': 'organics, other',
                'carbofuran': 'organics, pesticide',
                'chromium, hex': 'inorganics, minor, metals',
                'acidity, total (caco3)': 'inorganics, major, non-metals',
                '1,2-dichloropropane': 'organics, pesticide',
                'bromacil': 'organics, pesticide',
                'ethyl ether': 'organics, other',
                'silica d/sio2': 'inorganics, major, non-metals'}
