# Config file for automatic testing at travis-ci.org

sudo: false
language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=pep8

script: tox -e $TOX_ENV

install:
    - pip install tox

after_success:
    # Report coverage results to codecov.io
    - pip install codecov
    - codecov
