USE [master]
GO

IF EXISTS(select * from sys.databases where name='UGSWaterChemistry')
	DROP DATABASE [UGSWaterChemistry]

/****** Object:  Database [UGSWaterChemistry]    Script Date: 7/9/2015 11:30:30 AM ******/
CREATE DATABASE [UGSWaterChemistry]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UGSWaterChemistry', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\UGSWaterChemistry.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UGSWaterChemistry_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\UGSWaterChemistry_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [UGSWaterChemistry] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UGSWaterChemistry].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UGSWaterChemistry] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET ARITHABORT OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UGSWaterChemistry] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UGSWaterChemistry] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UGSWaterChemistry] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UGSWaterChemistry] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET RECOVERY FULL 
GO

ALTER DATABASE [UGSWaterChemistry] SET  MULTI_USER 
GO

ALTER DATABASE [UGSWaterChemistry] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UGSWaterChemistry] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UGSWaterChemistry] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UGSWaterChemistry] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UGSWaterChemistry] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UGSWaterChemistry] SET  READ_WRITE 
GO


